services:
  app:
    build: .

    container_name: atlasweather-app

    restart: unless-stopped

    environment:
      VIRTUAL_HOST: atlasweather.my.id,www.atlasweather.my.id
      LETSENCRYPT_HOST: atlasweather.my.id,www.atlasweather.my.id
      LETSENCRYPT_EMAIL: emailkamu@gmail.com

    expose:
      - "5000"

    networks:
      - proxy_network

networks:
  proxy_network:
    external: true